Fix Maven compilation error
This fixes the following Maven compilation error:

    [ERROR] COMPILATION ERROR :
    [INFO] -------------------------------------------------------------
    [ERROR] Source option 5 is no longer supported. Use 8 or later.
    [ERROR] Target option 5 is no longer supported. Use 8 or later.
    [INFO] 2 errors

Relevant StackOverflow thread: https://stackoverflow.com/a/58195741/